"""
Seed data/reference/{issuer_identity,security_identity,peer_groups}.csv
from live SEC data for the 21-stock watchlist.

Why this script exists
-----------------------
data/reference/*.csv currently ship as header-only schema stubs (see
src/sec/identity.py, src/fundamentals/peer_classification.py, and
src/sec/reference_io.py / src/fundamentals/peer_classification_io.py for
the modules that define and read/write this schema). This script performs
the one-time (then periodically re-run) bulk seed: for every ticker in the
project's 21-stock observation universe, fetch its real SEC Submissions
data, normalize it, and write it into the reference CSVs.

Watchlist source of truth: /projects/.../overview.md in Claude's memory
("Observation universe (21 stocks, 5 sectors -- as of 2026-09-07)"),
Information Technology(11) + Communication Services(3) + Financials(2) +
Healthcare(3) + Industrials/Defense(2) = 21. Reproduced here as a plain
list rather than re-derived, since this script has no access to that
memory store at run time.

CIK resolution deliberately does NOT hardcode CIK numbers for the 21
tickers -- SEC's bulk ticker->CIK file (fetch_company_tickers) is fetched
and used instead, via src.sec.identity.resolve_cik_for_ticker(). A ticker
this repo has previously looked up by hand is exactly the kind of value
that is easy to mistype once and then propagate silently forever; letting
the live bulk file be the single source of truth avoids that risk
entirely, at the cost of one extra HTTP call.

Network requirement
--------------------
This script needs outbound HTTPS to data.sec.gov and www.sec.gov. It is
NOT runnable from the Cowork cloud sandbox this project has been
developed in -- that sandbox's egress proxy explicitly denies
data.sec.gov at the policy layer (confirmed 2026-09-20 via the proxy's
own status endpoint: "gateway answered 403 to CONNECT (policy denial or
upstream failure)"). This mirrors every other real-SEC-data step in this
project (see e.g. tests/test_sec_fundamentals_pipeline.py,
tests/test_sec_history_real.py): it is meant to be run via a GitHub
Actions workflow_dispatch job with real network access
(.github/workflows/seed-identity-reference.yml), or locally by 명호. The
script itself has no test-suite dependency on live network -- its pure
logic (URL building, normalization, CSV serialization) is already covered
by tests/test_sec_identity.py, tests/test_sec_reference_io.py, and
tests/test_peer_classification_io.py using synthetic fixtures.

What this script deliberately does NOT do
-------------------------------------------
It seeds issuer_identity.csv and security_identity.csv fully (pure SEC
fact, no judgment involved). For peer_groups.csv it writes one
PENDING_REVIEW placeholder row per CIK with classification_source =
"SEC_SIC" and sector/industry/peer_group left BLANK -- it never invents a
sector, industry, or peer_group value, and in particular it never copies
sic_description into industry or peer_group (2026-09-20 revision; see
src/fundamentals/peer_classification.py's module docstring for why that
copy is exactly the raw-vs-managed boundary violation this design
forbids -- NFLX's raw SIC description "Services-Video Tape Rental" must
never become its industry or peer_group). The raw SIC code and
description remain fully available for a human reviewer via
issuer_identity.csv (joined by cik) and are also echoed into this row's
`notes` field purely for reviewer convenience -- never as a database
value read by any validation or lookup logic.

This script never writes a REVIEWED row -- assigning an economic
sector/industry/peer_group is a human/ChatGPT judgment call this script
has no authority to make, and this project's standing rule is never to
assert an economic classification without that judgment (parallels the
"SEC taxonomy는 실제 데이터 근거 없이 수정하지 않는다" rule already
applied elsewhere). The 21-stock Watchlist Universe's actual REVIEWED
classifications (as of the 2026-09-20 ChatGPT design round) are
maintained by hand in data/reference/peer_groups.csv, not generated by
this script.

CAUTION -- this script's write_peer_groups_csv() call is a full
OVERWRITE of peer_groups.csv, exactly as it was before this revision; it
does NOT read the existing file first and does NOT preserve any REVIEWED
rows already there. Re-running it today would blow away all 21 hand-
reviewed rows and replace them with blank PENDING_REVIEW placeholders.
Building a merge-and-preserve-REVIEWED-rows mode is explicitly OUT OF
SCOPE for this revision (see Framework v2.0 Step 9 scope note above) --
until that exists, do not re-run this script against a populated
peer_groups.csv without manually re-applying the REVIEWED rows
afterward, or diffing before committing.

Watchlist Universe vs Core Market Universe (2026-09-20)
----------------------------------------------------------
WATCHLIST_TICKERS below is the Watchlist Universe -- the 21 stocks 명호
is actually watching -- and this script's scope is deliberately limited
to it. It is NOT the Peer Universe: a company can have a fully REVIEWED
peer_group with zero other Watchlist members in it (see
peer_classification.py's PEER ADEQUACY section). Expanding comparison
coverage means adding real, financial-data-tracked external peers to a
separate, future "Core Market Universe" -- out of scope for this script
and for Framework v2.0 Step 9.
"""

from __future__ import annotations

import sys
from datetime import date, datetime, timezone
from pathlib import Path

from src.sec.fetcher import (
    fetch_and_cache_submissions,
    fetch_company_tickers,
    get_user_agent,
)
from src.sec.identity import (
    normalize_issuer_identity,
    validate_issuer_identity,
    validate_issuer_identity_provenance,
    normalize_security_identities,
    validate_security_identity,
    resolve_cik_for_ticker,
)
from src.sec.reference_io import (
    write_issuer_identity_csv,
    write_security_identity_csv,
)
from src.fundamentals.peer_classification import validate_reference_data
from src.fundamentals.peer_classification_io import write_peer_groups_csv


# =========================================================
# Configuration
# =========================================================

WATCHLIST_TICKERS = [
    # Information Technology (11)
    "MSFT", "AAPL", "NVDA", "AVGO", "INTC", "MU", "AMD", "PLTR", "ORCL", "SMCI", "CRWV",
    # Communication Services (3)
    "GOOGL", "META", "NFLX",
    # Financials (2)
    "BLK", "JPM",
    # Healthcare (3)
    "LLY", "UNH", "TEM",
    # Industrials/Defense (2)
    "LMT", "GE",
]

RAW_DIR = Path("data/raw/sec")
REFERENCE_DIR = Path("data/reference")


def main() -> None:
    user_agent = get_user_agent(default="invest-briefing-claude/0.1 chks7788@gmail.com")
    normalized_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    today = date.today().isoformat()

    print("=" * 60)
    print("Seeding identity reference data")
    print("=" * 60)

    # ---- Step 1: ticker -> CIK resolution (bulk file, not hardcoded) ----
    print(f"\nFetching SEC bulk ticker->CIK file for {len(WATCHLIST_TICKERS)} tickers...")
    company_tickers = fetch_company_tickers(user_agent=user_agent, verbose=False)

    ticker_to_cik: dict[str, str] = {}
    unresolved: list[str] = []
    for ticker in WATCHLIST_TICKERS:
        cik = resolve_cik_for_ticker(company_tickers, ticker)
        if cik is None:
            unresolved.append(ticker)
        else:
            ticker_to_cik[ticker] = cik

    if unresolved:
        raise RuntimeError(
            f"Could not resolve CIK for {len(unresolved)} watchlist ticker(s): "
            f"{unresolved}. Refusing to seed partial/guessed data -- check these "
            f"tickers manually against SEC's own bulk file before re-running."
        )

    print(f"[PASS] Resolved {len(ticker_to_cik)}/{len(WATCHLIST_TICKERS)} tickers to CIKs.")

    # ---- Step 2: fetch + cache raw Submissions per unique CIK ----
    unique_ciks = sorted(set(ticker_to_cik.values()))
    print(f"\nFetching SEC Submissions for {len(unique_ciks)} unique CIK(s)...")

    issuer_rows: list[dict] = []
    security_rows: list[dict] = []
    fetch_failures: list[tuple[str, str]] = []

    for cik in unique_ciks:
        try:
            raw, raw_path = fetch_and_cache_submissions(
                cik, raw_dir=RAW_DIR, user_agent=user_agent, verbose=False
            )
        except Exception as exc:  # noqa: BLE001 -- report and continue, don't abort the whole run
            fetch_failures.append((cik, str(exc)))
            print(f"  [FAIL] CIK {cik}: {exc}")
            continue

        issuer_row = normalize_issuer_identity(
            raw, source_raw_path=str(raw_path), normalized_at=normalized_at
        )
        issuer_failures = validate_issuer_identity(issuer_row) + validate_issuer_identity_provenance(issuer_row)
        if issuer_failures:
            raise RuntimeError(f"CIK {cik}: normalized issuer row failed validation: {issuer_failures}")
        issuer_rows.append(issuer_row)

        for sec_row in normalize_security_identities(raw):
            sec_failures = validate_security_identity(sec_row)
            if sec_failures:
                raise RuntimeError(f"CIK {cik}: normalized security row failed validation: {sec_failures}")
            security_rows.append(sec_row)

        print(f"  [PASS] CIK {cik}: {issuer_row['issuer_name']!r}, {len(normalize_security_identities(raw))} ticker(s)")

    if fetch_failures:
        print(f"\n[WARN] {len(fetch_failures)} CIK(s) failed to fetch -- continuing with the rest: {fetch_failures}")

    # ---- Step 3: write issuer_identity.csv / security_identity.csv ----
    write_issuer_identity_csv(issuer_rows, REFERENCE_DIR / "issuer_identity.csv")
    write_security_identity_csv(security_rows, REFERENCE_DIR / "security_identity.csv")
    print(f"\n[PASS] Wrote {len(issuer_rows)} issuer row(s), {len(security_rows)} security row(s).")

    # ---- Step 4: PENDING_REVIEW peer_groups.csv placeholder rows ----
    # Mechanical only -- one placeholder per CIK, never a REVIEWED
    # assertion, and never a sector/industry/peer_group value (2026-09-20
    # revision -- see this module's docstring for why sic_description must
    # never be copied into industry or peer_group). The raw SIC is echoed
    # into `notes` for reviewer convenience only; issuer_identity.csv
    # remains the Single Source of Truth for it.
    peer_rows: list[dict] = []
    for issuer_row in issuer_rows:
        sic = issuer_row.get("sic")
        if not sic:
            continue
        sic_description = issuer_row.get("sic_description")
        peer_rows.append(
            {
                "cik": issuer_row["cik"],
                "sector": None,
                "industry": None,
                "peer_group": None,
                "classification_source": "SEC_SIC",
                "classification_status": "PENDING_REVIEW",
                "mapping_version": "v1",
                "effective_from": today,
                "effective_to": None,
                "classification_available_date": today,
                "reviewed_at": None,
                "next_review_due": None,
                "review_reason": None,
                "notes": (
                    f"Auto-generated placeholder -- raw SEC SIC {sic} "
                    f"({sic_description!r}) preserved in issuer_identity.csv; "
                    "sector/industry/peer_group await MANUAL_REVIEW economic "
                    "classification and are never copied from SIC directly."
                ),
            }
        )

    reference_failures = validate_reference_data(issuer_rows, peer_rows)
    if reference_failures:
        raise RuntimeError(f"Seeded peer_groups.csv failed validate_reference_data(): {reference_failures}")

    write_peer_groups_csv(peer_rows, REFERENCE_DIR / "peer_groups.csv")
    print(f"[PASS] Wrote {len(peer_rows)} PENDING_REVIEW peer_groups.csv row(s) (0 REVIEWED -- human review still required).")

    print("\n" + "=" * 60)
    if fetch_failures or unresolved:
        print("[PARTIAL] Seeding completed with some failures -- see above.")
        sys.exit(1)
    print("[PASS] Identity reference seeding completed.")


if __name__ == "__main__":
    main()
